### ISSUE TITLE
Any plans to put it on jcenter?

### ISSUE THREAD

**Issue by Rainer-Lang** [danielnilsson9/color-picker-view#3]

**Comment by danielnilsson9** [comment]
Its beeing worked on, spent an increadable amount of time on this... but still not working. 
Files seems to be uplaoded correctly now but bintray UI keeps saying "this file is not yet published".

**Comment by Rainer-Lang** [comment]
Maybe this infos help... 
http://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

**Comment by danielnilsson9** [comment]
Its finally on jcenter, sorry for the delay. See  updated Readme for information.
